services:
  slam:
    image: romir/basketbuddy:slam
    restart: unless-stopped
    container_name: slam
    volumes:
      - ./config:/config
      - ./maps:/maps
    command: bash /bb/scripts/start.sh
