services:
  slam:
    image: romirk/basketbuddy:slam
    restart: unless-stopped
    container_name: slam
    volumes:
      - ./config:/config
      - ./maps:/maps
    devices:
      - /dev/ldlidar:/dev/ldlidar
    command: bash /bb/start.sh
