services:
  slam:
    image: romir/basketbuddy:slam
    restart: unless-stopped
    container_name: slam
    volumes:
      - ./maps:/maps
    devices:
      - /dev/ldlidar:/dev/ldlidar
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/ttyUSB0:/dev/ttyUSB0
    command: bash -c "cd /bb/ros_ws/ && cat ../slam.yaml && . install/local_setup.sh && ros2 launch basketbuddy main.launch.py"
    network_mode: host

